export const MAKES = 'MAKES'
export const BODY_STYLES = 'BODY_STYLES'
export const MAKE_SELECTED = 'MAKE_SELECTED'
export const BODY_STYLE_SELECTED = 'BODY_STYLE_SELECTED'
export const USERS_CMS = 'USERS_CMS'
export const DELETE_USER = 'DELETE_USER'
export const TOGGLE_USER = 'TOGGLE_USER'
export const USER_TO_BE_SAVED = 'USER_TO_BE_SAVED'